site_name: MOF_SL
site_url: http://192.168.203.116:8090
nav:
  - Inici: index.md
  - Sobre nosaltres: about.md
  - Guia Usuari: guia_usuari.md
theme:
  name: material
  locale: ca
  language: ca
markdown_extensions:
  - pymdownx.highlight:

extra_javascript:
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/prism.js
  - https://cdn.jsdelivr.net/npm/prismjs@1.24.1/components/prism-python.min.js